import test from 'node:test';
import assert from 'node:assert/strict';
import { existsSync, mkdirSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { chromium } from 'playwright-core';
import { createServer } from 'vite';

const executable=process.env.CI?undefined:[process.env.CHROME_PATH,'C:/Program Files/Google/Chrome/Application/chrome.exe','C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe','/usr/bin/google-chrome','/usr/bin/chromium','/usr/bin/chromium-browser','/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'].find(candidate=>candidate&&existsSync(candidate));
test('real browser editor: geometry, 3D volume, paint, selection, smooth transform and persistent library', {skip:!executable,timeout:90000},async()=>{
  const server=await createServer({configFile:false,cacheDir:path.join(tmpdir(),'hideaway-editor-vite-cache'),server:{host:'127.0.0.1',port:0},optimizeDeps:{exclude:['three']}});await server.listen();
  const address=server.httpServer!.address() as {port:number};const browser=await chromium.launch({executablePath:executable,headless:true,args:['--disable-background-timer-throttling']});
  const page=await browser.newPage({viewport:{width:1100,height:820}});const errors:string[]=[];page.on('pageerror',error=>errors.push(error.message));
  await page.addInitScript(() => localStorage.setItem('hideaway-language','zh-CN'));
  try{
    await page.route('**/editor-harness',route=>route.fulfill({contentType:'text/html',body:`<!doctype html><html lang="zh-CN"><meta charset="utf-8"><title>Editor acceptance</title><style>html,body{margin:0;overflow:hidden}#game{width:100vw;height:100vh;display:block}#ui{position:fixed;inset:0;pointer-events:none}</style><canvas id="game"></canvas><div id="ui"></div><script type="module">
      import * as THREE from '/node_modules/three/build/three.module.js';
      import { VoxelEditor } from '/src/voxel/editor.ts';
      import { createDefaultModel, createPresetModel, modelVolume } from '/src/voxel/model.ts';
      import { createModelView,updateModelView } from '/src/voxel/meshing.ts';
      import { listModels, makeThumbnail } from '/src/voxel/storage.ts';
      const canvas=document.querySelector('canvas'),scene=new THREE.Scene();scene.background=new THREE.Color('#cdd7bc');scene.add(new THREE.HemisphereLight(0xffffe9,0x617452,3));const sun=new THREE.DirectionalLight(0xffffff,2);sun.position.set(20,50,40);scene.add(sun);const camera=new THREE.PerspectiveCamera(55,innerWidth/innerHeight,.1,500),renderer=new THREE.WebGLRenderer({canvas,antialias:true});renderer.setSize(innerWidth,innerHeight);const actor=createModelView(createDefaultModel());scene.add(actor);const floor=new THREE.Mesh(new THREE.PlaneGeometry(150,150),new THREE.MeshStandardMaterial({color:'#9da77b'}));floor.rotation.x=-Math.PI/2;floor.position.y=-.08;scene.add(floor);let changed=0,checks=0,block=false;const notices=[];
      const editor=new VoxelEditor(scene,camera,canvas,document.querySelector('#ui'),{getPosition:()=>new THREE.Vector3(),getYaw:()=>0,validate:()=>{checks++;return{valid:!block,reason:'测试墙体阻挡'}},onChange:model=>{changed++;updateModelView(actor,model)},onClose:()=>{},notify:message=>notices.push(message)});editor.open(createDefaultModel());
      window.harness={editor,actor,camera,listModels,makeThumbnail,notices,reset:()=>editor.open(createDefaultModel()),block:value=>block=value,counts:()=>({changed,checks}),volume:()=>modelVolume(editor.model),screen:point=>{const v=new THREE.Vector3(...point).project(camera);return{x:(v.x+1)*innerWidth/2,y:(1-v.y)*innerHeight/2}},setPreset:kind=>editor.load(createPresetModel(kind))};
      function frame(){editor.update(1/60);renderer.render(scene,camera);requestAnimationFrame(frame)}frame();
      </script></html>`}));
    await page.goto(`http://127.0.0.1:${address.port}/editor-harness`);await page.waitForFunction(()=>!!(window as any).harness);
    const state=()=>page.evaluate(()=>({volume:(window as any).harness.volume(),model:(window as any).harness.editor.model,counts:(window as any).harness.counts()}));
    const point=async(x:number,y:number,z:number)=>page.evaluate(p=>(window as any).harness.screen(p),[x,y,z]);
    assert.equal((await state()).volume,512);
    let front=await point(.5,4.5,4.01);await page.mouse.click(front.x,front.y);assert.equal((await state()).volume,513);
    await page.keyboard.press('Control+z');assert.equal((await state()).volume,512);await page.keyboard.press('Control+y');assert.equal((await state()).volume,513);await page.keyboard.press('Control+z');
    // Drag across a front-face plane, then extend out of that plane using the wheel.
    front=await point(-1.5,3.5,4.01);const end=await point(1.5,5.5,4.01);await page.keyboard.down('Shift');await page.mouse.move(front.x,front.y);await page.mouse.down();await page.mouse.move(end.x,end.y,{steps:4});await page.mouse.wheel(0,-160);await page.mouse.wheel(0,-160);await page.mouse.up();await page.keyboard.up('Shift');
    const built=await state();assert.ok(built.volume>=524);const added=built.model.parts[0].cells.filter((c:any)=>c.z>=20);assert.ok(new Set(added.map((c:any)=>c.z)).size>=2,'drag volume has depth');
    await page.keyboard.press('Control+z');assert.equal((await state()).volume,512);
    // Same pointer path removes a real volume with Shift + right drag.
    front=await point(-1.5,3.5,4.01);await page.keyboard.down('Shift');await page.mouse.move(front.x,front.y);await page.mouse.down({button:'right'});await page.mouse.move(end.x,end.y,{steps:3});await page.mouse.wheel(0,160);await page.mouse.up({button:'right'});await page.keyboard.up('Shift');assert.ok((await state()).volume<512);await page.keyboard.press('Control+z');
    mkdirSync('.artifacts/editor-browser',{recursive:true});front=await point(.5,4.5,4.01);await page.mouse.move(front.x,front.y);await page.screenshot({path:'.artifacts/editor-browser/editor-geometry-target.png'});
    await page.locator('[data-tab="paint"]').click();await page.locator('[data-color="#af6870"]').click();front=await point(.5,4.5,4.01);await page.mouse.click(front.x,front.y);assert.ok((await state()).model.parts[0].cells.some((c:any)=>c.faceColors?.pz==='#af6870'));assert.ok((await state()).model.parts[0].cells.every((c:any)=>!c.faceColors?.nz&&c.color==='#b6c793'),'back and default color remain unchanged');
    await page.locator('[data-color="#486855"]').click();await page.keyboard.down('Alt');await page.mouse.click(front.x,front.y);await page.keyboard.up('Alt');assert.equal(await page.locator('[data-hex]').inputValue(),'#af6870');
    await page.mouse.click(front.x,front.y,{button:'right'});assert.equal((await state()).model.parts[0].cells.filter((c:any)=>c.faceColors?.pz==='#af6870').length,0);
    await page.locator('[data-action="bucket"]').click();await page.mouse.click(front.x,front.y);assert.equal((await state()).model.parts[0].cells.filter((c:any)=>c.faceColors?.pz==='#af6870').length,64);
    await page.locator('[data-color-mode]').selectOption('HSV');await page.getByLabel('H 颜色通道').fill('120');await page.getByLabel('H 颜色通道').press('Tab');assert.notEqual(await page.locator('[data-hex]').inputValue(),'#af6870');
    await page.locator('[data-color-mode]').selectOption('RGB');for(const [label,value]of [['R','0'],['G','128'],['B','255']]){await page.getByLabel(label+' 颜色通道').fill(value);await page.getByLabel(label+' 颜色通道').press('Tab');}assert.equal(await page.locator('[data-hex]').inputValue(),'#0080ff');
    await page.locator('[data-action="bucket"]').click();await page.locator('[data-brush]').focus();await page.keyboard.press('End');front=await point(.5,4.5,4.01);await page.mouse.move(front.x,front.y);await page.screenshot({path:'.artifacts/editor-browser/editor-paint-target.png'});await page.mouse.click(front.x,front.y);assert.ok((await state()).model.parts[0].cells.filter((c:any)=>c.faceColors?.pz==='#0080ff').length>8);await page.keyboard.press('Control+z');
    await page.locator('[data-tab="selection"]').click();front=await point(-2.5,2.5,4.01);const selectionEnd=await point(-.5,5.5,4.01);await page.mouse.move(front.x,front.y);await page.mouse.down();await page.mouse.move(selectionEnd.x,selectionEnd.y,{steps:3});await page.mouse.up();await page.locator('[data-action="split"]').click();assert.equal((await state()).model.parts.length,2);assert.equal((await state()).volume,512);assert.ok((await state()).model.parts.some((p:any)=>p.cells.length<50));await page.keyboard.press('Control+z');
    await page.locator('[data-action="all"]').click();await page.locator('[data-action="copy"]').click();assert.equal((await state()).model.parts.length,2);
    await page.locator('[data-numeric] summary').click();await page.locator('[data-transform-number]').fill('0.1');await page.keyboard.down('Shift');await page.locator('[data-transform-apply]').click();await page.keyboard.up('Shift');assert.ok((await state()).model.parts.some((p:any)=>Math.abs(p.position[0]-1.1)<1e-8));
    await page.locator('[data-transform-mode]').selectOption('rotate');await page.locator('[data-numeric] summary').click();await page.locator('[data-transform-axis]').selectOption('y');await page.locator('[data-transform-number]').fill('1');await page.keyboard.down('Shift');await page.locator('[data-transform-apply]').click();await page.keyboard.up('Shift');assert.ok((await state()).model.parts.some((p:any)=>Math.abs(p.rotation[1]-Math.PI/180)<1e-7));
    await page.locator('[data-numeric] summary').click();await page.locator('[data-mirror="x"]').click();await page.locator('[data-name]').fill('浏览器验收模型');await page.locator('[data-action="save"]').click();await page.waitForFunction(async()=>((await (window as any).harness.listModels()).length===1));
    await page.locator('[data-tab="geometry"]').click();await page.locator('[data-action="library"]').click();await page.locator('.ve-model-card').waitFor();assert.equal(await page.locator('.ve-model-card h3').innerText(),'浏览器验收模型');assert.ok((await page.locator('.ve-model-card img').getAttribute('src'))?.startsWith('data:image/png'));
    await page.locator('.ve-model-card button').first().click();assert.equal((await state()).model.name,'浏览器验收模型');assert.equal((await state()).model.version,2);assert.ok((await state()).model.parts.some((p:any)=>p.cells.some((c:any)=>c.faceColors)),'face data survives library round trip');
    await page.locator('[data-action="library"]').click();await page.locator('.voxel-library').waitFor();await page.keyboard.press('Escape');assert.equal(await page.locator('.voxel-library').count(),0);assert.equal(await page.locator('.voxel-editor').isVisible(),true);
    // An environment rejection leaves the current model and history untouched.
    await page.evaluate(()=>(window as any).harness.block(true));const before=await state();await page.locator('[data-preset]').selectOption('plant');const rejected=await state();assert.deepEqual(rejected.model,before.model);assert.ok(await page.locator('.ve-rejected').count());await page.evaluate(()=>(window as any).harness.block(false));
    mkdirSync('.artifacts/editor-browser',{recursive:true});await page.screenshot({path:'.artifacts/editor-browser/editor-browser.png'});
    // Locate each rendered handle by raycast, then use real browser mouse events to drag it.
    const handle=async(axis:string)=>page.evaluate(axis=>{
      const h=(window as any).harness,c=h.editor.controls,p=c.object.position.clone();c.object.localToWorld(p.set(0,0,0));p.project(h.camera);
      const cx=(p.x+1)*innerWidth/2,cy=(1-p.y)*innerHeight/2,ray=c.getRaycaster(),matches:any[]=[];
      for(let dx=-95;dx<=95;dx+=3)for(let dy=-95;dy<=95;dy+=3){if(dx*dx+dy*dy<400)continue;const x=cx+dx,y=cy+dy;ray.setFromCamera({x:x/innerWidth*2-1,y:1-y/innerHeight*2},h.camera);const hit=ray.intersectObject(c._gizmo.picker[c.mode],true).find((i:any)=>i.object.visible);if(hit?.object.name===axis)matches.push({x,y,d:dx*dx+dy*dy});}
      matches.sort((a,b)=>b.d-a.d);if(!matches.length)throw new Error('Rendered handle not hittable: '+axis);return matches[Math.floor(matches.length*.2)];
    },axis);
    const selectReset=async()=>{await page.evaluate(()=>(window as any).harness.reset());await page.locator('[data-tab="selection"]').click();await page.locator('[data-action="all"]').click();await page.locator('[data-transform-mode]').selectOption('move');await page.waitForTimeout(80);};
    const dragHandle=async(axis:string,dx:number,dy:number,options:{shift?:boolean;cancel?:boolean;block?:boolean}={})=>{const start=await handle(axis);if(options.shift)await page.keyboard.down('Shift');await page.mouse.move(start.x,start.y);await page.mouse.down();assert.equal(await page.evaluate(()=>(window as any).harness.editor.gizmoDragging),true,'mouse acquired '+axis+' handle');if(options.block)await page.evaluate(()=>(window as any).harness.block(true));await page.mouse.move(start.x+dx,start.y+dy,{steps:8});if(options.cancel)await page.keyboard.press('Escape');await page.mouse.up();if(options.shift)await page.keyboard.up('Shift');if(options.block)await page.evaluate(()=>(window as any).harness.block(false));};
    await selectReset();const pristine=(await state()).model;await page.screenshot({path:'.artifacts/editor-browser/editor-move-gizmo.png'});
    await dragHandle('X',24,0);const snapped=(await state()).model;assert.notDeepEqual(snapped,pristine);assert.ok(snapped.parts[0].position.every((n:number)=>Number.isInteger(n)),'default translation snaps to cells');
    await page.keyboard.press('Control+z');assert.deepEqual((await state()).model,pristine,'one drag is exactly one undo');assert.equal(await page.locator('[data-action="undo"]').isDisabled(),true);
    await page.locator('[data-action="all"]').click();await page.waitForTimeout(80);await dragHandle('X',13,0,{shift:true});assert.ok((await state()).model.parts[0].position.some((n:number)=>Math.abs(n-Math.round(n))>.001),'Shift gives continuous translation');
    await selectReset();const cancelBase=(await state()).model;await dragHandle('X',30,0,{cancel:true});assert.deepEqual((await state()).model,cancelBase,'Esc restores drag start');assert.equal(await page.locator('[data-action="undo"]').isDisabled(),true);
    await dragHandle('X',30,0,{block:true});assert.deepEqual((await state()).model,cancelBase,'blocked drag never enters history');
    await page.locator('[data-action="all"]').click();await page.waitForTimeout(80);await dragHandle('X',350,0);assert.deepEqual((await state()).model,cancelBase,'ending outside 32 cube must not commit an earlier valid preview');
    await page.locator('[data-action="all"]').click();await page.waitForTimeout(80);await dragHandle('XZ',20,5,{shift:true});assert.notDeepEqual((await state()).model,cancelBase,'plane drag transforms model');
    await selectReset();await page.locator('[data-transform-mode]').selectOption('rotate');await page.waitForTimeout(80);const rotateBase=(await state()).model;await page.screenshot({path:'.artifacts/editor-browser/editor-rotate-gizmo.png'});await dragHandle('Y',25,0);const rotated=(await state()).model;assert.notDeepEqual(rotated,rotateBase);assert.ok(Math.abs(rotated.parts[0].rotation[1]/(Math.PI/12)-Math.round(rotated.parts[0].rotation[1]/(Math.PI/12)))<1e-6,'rotation snaps to 15 degrees');assert.deepEqual(rotated.parts[0].cells,rotateBase.parts[0].cells,'free transform never resamples cells');
    await page.keyboard.press('Control+z');assert.deepEqual((await state()).model,rotateBase);
    await page.locator('[data-action="all"]').click();await page.waitForTimeout(80);await dragHandle('Y',17,0,{shift:true});const smoothAngle=(await state()).model.parts[0].rotation[1]/(Math.PI/12);assert.ok(Math.abs(smoothAngle-Math.round(smoothAngle))>.001,'Shift bypasses angle snap');
    // Legacy library rows stay readable beside version 2 rows; thumbnail changes follow face colors.
    const migration=await page.evaluate(async()=>{const h=(window as any).harness,rows=await h.listModels(),old=structuredClone(rows[0]);old.id='legacy';old.name='Legacy';old.model.version=1;old.model.parts.forEach((p:any)=>p.cells.forEach((c:any)=>delete c.faceColors));localStorage.setItem('hideaway.models.v1',JSON.stringify([old,...rows]));const listed=await h.listModels();return {versions:listed.map((row:any)=>row.model.version),thumbnailChanged:h.makeThumbnail(old.model)!==h.makeThumbnail(rows[0].model)};});assert.deepEqual(migration.versions.sort(),[1,2]);assert.equal(migration.thumbnailChanged,true,'thumbnail includes per-face colors');
    assert.deepEqual(errors,[]);
    await page.keyboard.press('Tab');assert.equal(await page.locator('.voxel-editor').isVisible(),false);
  }finally{await browser.close();await server.close();}
});
