import {build,preview} from 'vite';
import {existsSync} from 'node:fs';
import {chromium} from 'playwright-core';import {mkdir,writeFile} from 'node:fs/promises';import assert from 'node:assert/strict';
const executable=[process.env.CHROME_PATH,'C:/Program Files/Google/Chrome/Application/chrome.exe','C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe','/usr/bin/google-chrome','/usr/bin/chromium','/usr/bin/chromium-browser','/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'].find(candidate=>candidate&&existsSync(candidate));
if(!executable)throw new Error('Install Chrome / Edge or set CHROME_PATH before running the round soak.');
await mkdir('.artifacts',{recursive:true});
await build({mode:'test',build:{outDir:'.artifacts/soak-build'}});
const server=await preview({mode:'test',build:{outDir:'.artifacts/soak-build'},preview:{host:'127.0.0.1',port:0}});const address=server.httpServer.address();const browser=await chromium.launch({executablePath:executable,headless:true,args:['--disable-background-timer-throttling','--disable-renderer-backgrounding','--disable-backgrounding-occluded-windows']});const page=await browser.newPage({viewport:{width:1280,height:800}});const errors=[],samples=[];page.on('pageerror',e=>errors.push(e.message));let passed=false;
try{await page.goto('http://127.0.0.1:'+address.port,{waitUntil:'networkidle'});await page.waitForFunction(()=>window.__game);await page.locator('[data-action=settings]').click();await page.locator('[name=role]').selectOption('hunter');await page.locator('[name=players]').fill('8');await page.locator('[name=hunters]').fill('1');await page.locator('[name=preparationSeconds]').fill('360');await page.locator('[name=huntSeconds]').fill('480');await page.locator('button[type=submit]').click();await page.locator('[data-action=hunt]').click();const started=Date.now();let lastPhase='';while(Date.now()-started<950000){await page.waitForTimeout(10000);let snap=await page.evaluate(()=>window.__game.snapshot());samples.push({...snap,wallSeconds:(Date.now()-started)/1000});if(snap.phase!==lastPhase){lastPhase=snap.phase;console.log('PHASE',JSON.stringify({phase:snap.phase,wallSeconds:(Date.now()-started)/1000,elapsed:snap.elapsed,round:snap.round,fps:snap.fps,alive:snap.actors.filter(a=>a.alive).length}));await page.screenshot({path:'.artifacts/soak-'+snap.phase+'.png'});await writeFile('.artifacts/soak-progress.json',JSON.stringify(samples,null,2))}if(snap.round>=2){passed=true;break}assert.ok(snap.actors.every(a=>a.position.every(Number.isFinite)&&a.position[1]>-40),'no invalid or fallen actor');if(!snap.locked&&snap.phase!=='reveal'){const btn=page.locator('#unlock-hint button');if(await btn.isVisible())await btn.click()}if(errors.length)throw new Error(errors.join('\n'));}assert.ok(passed,'default duration round reached next round');const hunt=samples.find(s=>s.phase==='hunt');assert.ok(hunt&&hunt.wallSeconds>=359);assert.ok(samples.some(s=>s.phase==='reveal'));assert.ok(samples.at(-1).actors.some(a=>a.total>0));console.log('SOAK_PASS',JSON.stringify({elapsedSeconds:(Date.now()-started)/1000,errors,samples:samples.length}));}catch(e){console.log('SOAK_FAIL',String(e));process.exitCode=1}finally{await writeFile('.artifacts/soak-result.json',JSON.stringify({passed,errors,samples},null,2));await browser.close();server.httpServer.close()}
