import * as THREE from 'three';import type {Actor} from './runtime.ts';import type {MapWorld,Phase,WeaponId} from './contracts.ts';import {WEAPONS,damageForDistance,wrongHitPenalty,SoundSystem} from './actors/index.ts';import type {Effects} from './effects.ts';
import {PREPARATION_ROOM} from './rules.ts';
import type {PracticeRange} from './practice-range.ts';
export class Combat {
 actors:Actor[]=[];map:MapWorld;sound:SoundSystem;effects:Effects;onDamage:(actor:Actor,killer?:Actor)=>void;onHit:(actor:Actor)=>void;
 onPracticeHit:(actor:Actor,target:number,points?:number,total?:number)=>void=()=>{};
 constructor(map:MapWorld,sound:SoundSystem,effects:Effects,onDamage:(actor:Actor,killer?:Actor)=>void,onHit:(actor:Actor)=>void){this.map=map;this.sound=sound;this.effects=effects;this.onDamage=onDamage;this.onHit=onHit}
 update(actor:Actor,dt:number){actor.fireCooldown=Math.max(0,actor.fireCooldown-dt);actor.shotTimer=Math.max(0,actor.shotTimer-dt);actor.meleeTimer=Math.max(0,actor.meleeTimer-dt);actor.hurtTimer=Math.max(0,actor.hurtTimer-dt);actor.switchTimer=Math.max(0,actor.switchTimer-dt);actor.stun=Math.max(0,actor.stun-dt);actor.knockdown=Math.max(0,(actor.knockdown??0)-dt);actor.ramCooldown=Math.max(0,actor.ramCooldown-dt);if(actor.reloadTimer>0){actor.reloadTimer=Math.max(0,actor.reloadTimer-dt);if(actor.reloadTimer===0){const amount=Math.min(WEAPONS[actor.gun].magazine-actor.ammo,actor.reserve);actor.ammo+=amount;actor.reserve-=amount}}}
 reload(actor:Actor){if(actor.weapon==='knife'||actor.reloadTimer>0||actor.reserve<=0||actor.ammo>=WEAPONS[actor.gun].magazine||!actor.alive)return;actor.reloadTimer=WEAPONS[actor.gun].reload;this.sound.play('reload',actor.position,actor.gun)}
 switch(actor:Actor,weapon:WeaponId){if(actor.weapon===weapon)return;actor.weapon=weapon;actor.reloadTimer=0;actor.switchTimer=.35;this.sound.play('switch',actor.position)}
 supplyWeapon(actor:Actor,weapon:WeaponId){if(actor.role!=='hunter'||!actor.alive)return;if(weapon!=='knife')actor.gun=weapon;this.switch(actor,weapon);actor.ammo=WEAPONS[actor.gun].magazine;actor.reserve=WEAPONS[actor.gun].reserve;actor.reloadTimer=0;actor.fireCooldown=0}
 damage(victim:Actor,amount:number,killer?:Actor){if(!victim.alive)return;victim.hp=Math.max(0,victim.hp-amount);victim.hurtTimer=.3;this.sound.play('hit',victim.position);this.effects.burst(victim.position.clone().add(new THREE.Vector3(0,8,0)),victim.role==='hunter'?0xd97256:0xf6dc87,7);if(victim.hp<=0){victim.alive=false;victim.deadTime=0;if(killer)killer.score+=100;this.effects.burst(victim.position.clone().add(new THREE.Vector3(0,8,0)),0xf2d689,24)}this.onDamage(victim,killer)}
 shoot(actor:Actor,direction:THREE.Vector3,phase:Phase){const training=phase==='preparation',room=PREPARATION_ROOM,p=actor.position;const inPreparation=p.x>=room.minX&&p.x<=room.maxX&&p.z>=room.minZ&&p.z<=room.maxZ&&p.y>=room.minY&&p.y<room.maxY;if(actor.role!=='hunter'||!actor.alive||phase!=='hunt'&&!training||training&&!inPreparation||!direction.toArray().every(Number.isFinite)||direction.lengthSq()<.001||actor.fireCooldown>0||actor.reloadTimer>0||actor.switchTimer>0||actor.stun>0)return false;const weapon=WEAPONS[actor.weapon];if(actor.weapon!=='knife'&&actor.ammo<=0){this.reload(actor);return false}if(actor.weapon!=='knife')actor.ammo--;actor.fireCooldown=weapon.interval;actor.shotTimer=.16;if(actor.weapon==='knife')actor.meleeTimer=.4;this.sound.play(actor.weapon==='knife'?'knife':'shot',actor.position,actor.weapon);
 const origin=actor.position.clone().add(new THREE.Vector3(0,actor.crouch?26:40,0));const ray=new THREE.Raycaster();ray.layers.enable(1);let hitWorld=false,hitTarget=false;
 this.map.group.updateMatrixWorld(true);for(const a of this.actors)a.visual.updateMatrixWorld(true);const practiceHits=new Set<number>();
 for(let p=0;p<weapon.pellets;p++){const spread=weapon.spread*(actor.aim?.45:1);const dir=direction.clone().add(new THREE.Vector3((Math.random()-.5)*spread,(Math.random()-.5)*spread,(Math.random()-.5)*spread)).normalize();ray.set(origin,dir);ray.far=weapon.range;let closestDistance=weapon.range;let victim:Actor|undefined;const worldHit=ray.intersectObject(this.map.group,true).find(h=>{if(h.distance<=.3)return false;for(let object:THREE.Object3D|null=h.object;object;object=object.parent)if(!object.visible)return false;return true});if(worldHit){closestDistance=worldHit.distance;hitWorld=true}if(!training)for(const target of this.actors){if(target===actor||!target.alive||target.role!=='hider')continue;const hit=ray.intersectObject(target.visual,true)[0];if(hit&&hit.distance<closestDistance){closestDistance=hit.distance;victim=target}}
  const end=origin.clone().addScaledVector(dir,closestDistance);if(actor.weapon!=='knife')this.effects.trace(origin.clone().addScaledVector(dir,8),end);if(victim){this.damage(victim,damageForDistance(weapon,closestDistance),actor);actor.score+=5;hitTarget=true;this.onHit(actor)}else if(worldHit){const target=worldHit.object.userData.practiceTargetIndex??worldHit.object.userData.practiceTarget;if(training&&Number.isInteger(target)&&target>=0){if(!practiceHits.has(target)){practiceHits.add(target);const range=this.map.group.userData.practiceRange as PracticeRange|undefined;const feedback=range?.hitTarget(target,end);if(this.effects.targetImpact)this.effects.targetImpact(end,dir);else this.effects.burst(end,0xf6dc87,8);this.sound.play('targetHit',end);if(!range||feedback){if(!range){worldHit.object.userData.practiceHits=(worldHit.object.userData.practiceHits??0)+1;worldHit.object.userData.practiceHitAt=performance.now()}this.onPracticeHit(actor,target,feedback?.points,feedback?.total)}}}else this.effects.burst(end,0xd6c0a0,3)}
 }
 if(!training&&!hitTarget&&hitWorld)this.damage(actor,wrongHitPenalty(weapon,'world'));if(actor.weapon!=='knife'&&actor.ammo<=0)this.reload(actor);return true;
 }
 ram(hider:Actor,hunter:Actor){if(!hider.alive||!hunter.alive||!hider.sprint||hider.ramCooldown>0||hider.stun>0)return false;const delta=hunter.position.clone().sub(hider.position);if(Math.abs(delta.y)>30||delta.length()>22||Math.hypot(hider.velocity.x,hider.velocity.z)<40||hider.velocity.dot(delta)<=0)return false;const cells=hider.model.parts.reduce((sum,p)=>sum+p.cells.length,0);const strength=70+Math.min(100,cells/180);hunter.velocity.add(delta.setY(.12).normalize().multiplyScalar(strength));hunter.stun=Math.min(1.2,.4+cells/15000);if(cells>=4096)hunter.knockdown=hunter.stun;hunter.hurtTimer=.3;hider.ramCooldown=1.5;hider.score+=25;this.sound.play('hit',hunter.position);this.effects.burst(hunter.position.clone().add(new THREE.Vector3(0,20,0)),0xe8c279,10);return true}
}
