import {sampleRoomPosition} from './world/spaces.ts';
import {translate} from './i18n.ts';
import {aimBot} from './bot-aim.ts';
import * as THREE from 'three';
import {createWorld} from './world/index.ts';
import {layout,type DesignLayout} from './world/design-layout.ts';
import {setSceneModelProvider} from './voxel/storage.ts';
import {Recoil} from './recoil.ts';
import type {PracticeRange} from './practice-range.ts';
import type {WeaponRack} from './weapon-rack.ts';
import {MOTION} from './movement.ts';
import {canTauntPhase,needsPreparationReturn} from './rules.ts';
import {createDefaultModel,createPresetModel,cloneModel,modelBounds,modelVolume,validateModel,createModelView,updateModelView,disposeModelView,VoxelEditor,openModelLibrary} from './voxel/index.ts';
import {createHunterRig,WEAPONS,SoundSystem,preloadHunterAssets} from './actors/index.ts';
import {Rendering} from './rendering.ts';import {Physics} from './physics.ts';import {Input} from './input.ts';import {Session,DEFAULT_SETTINGS,normalizeSettings,scoreRate,tauntReady} from './session.ts';import {UI} from './ui.ts';import {Effects} from './effects.ts';import {Combat} from './combat.ts';import {BotDirector} from './bots.ts';
import type {Actor} from './runtime.ts';import type {GameSettings,MapWorld,VoxelModel,Phase,Vec3,WeaponId} from './contracts.ts';
const UP=new THREE.Vector3(0,1,0),HUNTER_BOUNDS={min:[-9,0,-7] as Vec3,max:[9,48,7] as Vec3};
const NAMES=['你','小栗','阿橙','薄荷','团子','小满','木木','南风'];
export class Game {
 rendering:Rendering;physics:Physics;input:Input;session:Session;ui:UI;map:MapWorld;sound=new SoundSystem();effects:Effects;combat:Combat;bots:BotDirector;editor:VoxelEditor;
 inspectionActive=false;recoil=new Recoil();botRecoil=new Map<number,Recoil>();eyeHeight=42;cameraStride=0;
 climbers=new Map<number,{normal:THREE.Vector3;cooldown:number;active:boolean}>();climbFeedbackAt=-Infinity;lastEditSound=0;roleRandom:()=>number=Math.random;quickTest=false;actors:Actor[]=[];settings:GameSettings;selectedModel=createDefaultModel();firstPerson=false;yaw=0;pitch=-.12;running=false;lastTime=0;accumulator=0;fps=60;frameCount=0;fpsTimer=0;hudTimer=0;menuTime=0;nearHunter=false;revealOrder:Actor[]=[];highlight:THREE.BoxHelper;disposed=false;libraryClose?:()=>void;
 constructor(rendering:Rendering,physics:Physics){this.rendering=rendering;this.physics=physics;this.settings=this.readSettings();this.selectedModel.name=translate(this.selectedModel.name);for(const part of this.selectedModel.parts)part.name=translate(part.name);this.session=new Session(this.settings);this.input=new Input(rendering.renderer.domElement);this.map=createWorld();rendering.scene.add(this.map.group);this.map.randomize(2026,this.settings.randomRatio);setSceneModelProvider(()=>this.map.group.userData.mimicModels??[]);physics.loadWorld(this.map.colliders);this.effects=new Effects(rendering.scene);this.bots=new BotDirector(this.map,physics);
  this.ui=new UI(document.querySelector('#ui')!,{start:(mode,quick=false)=>this.start(mode,quick),menu:()=>this.menuAction(),resume:()=>this.resume(),settings:s=>this.setSettings(s),models:()=>void this.models(),end:()=>this.end(),edit:()=>this.toggleEditor(),next:()=>{if(this.session.phase==='reveal')this.session.remaining=0},audio:cue=>{void this.sound.init().then(()=>{if(cue)this.sound.play('ui')})},audioPreview:(volume,musicVolume)=>{this.sound.setVolume(volume);this.sound.setMusicVolume(musicVolume)}},this.settings);
  this.combat=new Combat(this.map,this.sound,this.effects,(a,k)=>this.damaged(a,k),a=>{if(a.id===0)this.ui.hit()});
  this.combat.onPracticeHit=(a,target,points,total)=>{if(a.id===0){this.ui.hit();this.ui.toast(`靶 ${target+1} 击倒 · +${points??0} · 练靶累计 ${total??0}`)}};
  this.editor=new VoxelEditor(rendering.scene,rendering.camera,rendering.renderer.domElement,document.querySelector('#editor-root')!,{getPosition:()=>this.player?.position??new THREE.Vector3(),getYaw:()=>this.player?.yaw??0,validate:(candidate,previous)=>{const valid=validateModel(candidate);if(!valid.valid)return valid;return this.physics.validateEdit({...candidate,pivot:previous.pivot},previous,this.player.position,this.player.yaw)},onChange:model=>this.changeModel(model),onClose:()=>{this.ui.hud();if(this.player?.alive)this.resume()},notify:message=>this.ui.toast(message,false)});
  this.highlight=new THREE.BoxHelper(new THREE.Object3D(),0xffdb8c);this.highlight.material=new THREE.LineBasicMaterial({color:0xffdb8c,transparent:true,opacity:.9,depthTest:false});this.highlight.layers.set(2);this.highlight.renderOrder=100;this.highlight.visible=false;rendering.scene.add(this.highlight);rendering.quality(this.settings.quality==='high');this.sound.setVolume(this.settings.volume);this.sound.setMusicVolume(this.settings.musicVolume);this.ui.menu();this.menuCamera(0);rendering.renderer.domElement.addEventListener('click',()=>{if(this.running&&!this.editor.active&&this.ui.screen==='game'&&!this.input.locked)this.resume()});requestAnimationFrame(t=>this.frame(t));
 }
 static async create(){const rendering=new Rendering(document.querySelector<HTMLCanvasElement>('#game')!);const progress=(message:string)=>{const label=document.querySelector('.loading p');if(label&&!document.querySelector('#boot-error')){label.setAttribute('data-loading-message',message);label.textContent=translate(message)}};const [physics]=await Promise.all([Physics.create(),preloadHunterAssets(progress)]);return new Game(rendering,physics)}
 get player(){return this.actors[0]}
 preparationPosition(hunterIndex:number):Vec3{const spawns=(this.map.group.userData.spawns??layout.spawns) as DesignLayout['spawns'];const slots=spawns.preparationSlots;return [...(slots.length?slots[Math.max(0,hunterIndex)%slots.length]:spawns.hunterPreparation)]}
 roundModel(index:number,scene=(this.map.group.userData.mimicModels??[]) as VoxelModel[]):VoxelModel{if(index===0)return cloneModel(this.selectedModel);const valid=scene.filter(model=>validateModel(model).valid);return valid.length?cloneModel(valid[(index+this.session.round)%valid.length]):createPresetModel(['plant','book','crate','lamp','cup','chair'][(index+this.session.round)%6])}
 nearWeaponStation():boolean{const p=this.player;if(!p?.alive||p.role!=='hunter'||this.session.phase!=='preparation')return false;const features=(this.map.group.userData.preparationFeatures??layout.preparationFeatures) as DesignLayout['preparationFeatures'];const center=p.position.clone().add(new THREE.Vector3(0,(p.bounds.min[1]+p.bounds.max[1])/2,0));return center.distanceTo(new THREE.Vector3(...features.weaponStation.interaction))<=features.weaponStation.activationDistance}
 aimAngles(){return{pitch:THREE.MathUtils.clamp(this.pitch+(this.player?.role==='hunter'?(this.recoil?.pitch??0):0),-1.38,1.35),yaw:this.yaw+(this.player?.role==='hunter'?(this.recoil?.yaw??0):0)}}
 aimDirection(){const {pitch,yaw}=this.aimAngles();return new THREE.Vector3(0,0,-1).applyEuler(new THREE.Euler(pitch,yaw,0,'YXZ'))}
 rackSelection():WeaponId|null{if(!this.nearWeaponStation())return null;const rack=this.map.group.userData.weaponRack as WeaponRack|undefined;const p=this.player,origin=p.position.clone().add(new THREE.Vector3(0,p.crouch?27:42,0));return rack?.pick(origin,this.aimDirection())??null}
 takeRackWeapon():boolean{const weapon=this.rackSelection();if(!weapon)return false;this.combat.supplyWeapon(this.player,weapon);this.ui.toast(`已取用${WEAPONS[weapon].name}，弹药已补充`);return true}
 readSettings(){try{return normalizeSettings(JSON.parse(localStorage.getItem('hideaway-settings')??'{}'))}catch{return{...DEFAULT_SETTINGS}}}
 setSettings(settings:GameSettings){this.settings=settings;try{localStorage.setItem('hideaway-settings',JSON.stringify(settings))}catch{this.ui.toast('浏览器没有允许保存设置')}this.rendering.quality(settings.quality==='high');this.sound.setVolume(settings.volume);this.sound.setMusicVolume(settings.musicVolume)}
 start(mode:'practice'|'hunt',quick=false){this.inspectionActive=false;this.libraryClose?.();this.libraryClose=undefined;this.editor.close();this.input.clear();void this.sound.init();this.clearActors();this.quickTest=quick;this.session=new Session(quick?{...this.settings,role:'hunter',preparationSeconds:5,huntSeconds:45}:this.settings,this.roleRandom);this.session.start(mode);this.running=true;this.createRound(false);this.ui.hud();this.resume();this.announceRole()}
 announceRole(){this.ui.toast(this.session.phase==='practice'?'自由练习：Tab 建模 · Ctrl 靠墙攀爬 · Space 蹬离':`第 ${this.session.round} 局 · 本轮你是${this.player.role==='hunter'?'猎人：瞄准武器架左键取枪 · 靶场自由射击 · R 换弹':'躲藏者：Tab 建模 · Ctrl 靠墙攀爬 · 猎杀开始后可发声'}${this.quickTest?'（短流程测试）':''}`)}
 clearActors(){this.climbers.clear();for(const a of this.actors){this.rendering.scene.remove(a.visual);if(a.rig)a.rig.dispose();else disposeModelView(a.visual);this.physics.removeActor(a.physical)}this.actors=[];this.combat.actors=this.actors}
 createRound(carry:boolean){const settings=this.session.settings;const totals=carry?this.actors.map(a=>a.total+a.score):[];this.clearActors();this.bots.reset();this.map.randomize(2026+this.session.round*7919,settings.randomRatio);this.physics.loadWorld(this.map.colliders);const practice=this.session.phase==='practice';const count=this.session.roles.length;const sceneModels=(this.map.group.userData.mimicModels??[]) as VoxelModel[];let hunterSlot=0;this.input.clear();this.nearHunter=false;this.revealOrder=[];this.recoil?.reset();this.botRecoil?.clear();this.eyeHeight=42;this.cameraStride=0;(this.map.group.userData.practiceRange as PracticeRange|undefined)?.reset();
  for(let i=0;i<count;i++){const role=this.session.roles[i];const model=this.roundModel(i,sceneModels);const preparingHunter=role==='hunter'&&!practice;const source=preparingHunter?this.preparationPosition(hunterSlot++):this.map.hiderSpawn;const position=new THREE.Vector3(...source);if(!preparingHunter){position.x+=(i%3-1)*30;position.z+=Math.floor(i/3)*25;}const bounds=role==='hunter'?HUNTER_BOUNDS:modelBounds(model);position.y+=.2-Math.min(0,bounds.min[1]);const physical=this.physics.addActor(i,position,bounds);const rig=role==='hunter'?createHunterRig([0x3f7770,0xb98058,0x69838b][i%3]):undefined;const visual=rig?.group??createModelView(model);visual.position.copy(position);this.rendering.scene.add(visual);const gun=i===0?settings.gun:(['pistol','smg','shotgun'] as const)[i%3];const actor:Actor={id:i,name:NAMES[i],role,position:physical.position,velocity:new THREE.Vector3(),yaw:0,bounds,volume:modelVolume(model),hp:100,alive:true,score:0,total:totals[i]??0,model,physical,visual,rig,gun,weapon:gun,ammo:WEAPONS[gun].magazine,reserve:WEAPONS[gun].reserve,fireCooldown:0,reloadTimer:0,shotTimer:0,meleeTimer:0,hurtTimer:0,switchTimer:0,stun:0,knockdown:0,lastTaunt:-Infinity,lastForced:0,lastStep:0,ramCooldown:0,pitch:0,aim:false,sprint:false,crouch:false,deadTime:0,previousYaw:0};this.actors.push(actor)}this.combat.actors=this.actors;this.session.revealDuration=Math.max(9,this.actors.filter(a=>a.role==='hider').length*3.5);this.highlight.visible=false;this.firstPerson=this.player.role==='hunter';this.yaw=0;this.pitch=-.12;this.physics.step(1/60)}
 menuAction(){if(this.ui.screen==='game'){this.input.unlock();this.ui.pause();return}this.returnMenu()}
 returnMenu(){this.inspectionActive=false;this.running=false;this.editor.close();this.libraryClose?.();this.libraryClose=undefined;this.input.unlock();this.session.transition('menu');this.highlight.visible=false;this.clearActors();this.ui.menu()}
 resume(){if(!this.running||this.session.phase==='sessionEnd')return;void this.sound.init();if(this.ui.screen==='pause')this.ui.hud();this.input.clear();void this.input.lock()}
 end(){this.editor.close();this.input.unlock();this.session.end();this.running=false;this.ui.totals(this.actors);this.highlight.visible=false}
 toggleEditor(){if(!this.player?.alive||this.player.role!=='hider'||!['practice','preparation','hunt'].includes(this.session.phase))return;if(this.editor.active){this.editor.close();return}this.input.unlock();this.input.clear();this.player.visual.visible=true;const material=this.player.visual.userData.voxelState?.material as THREE.MeshStandardMaterial|undefined;if(material){if(material.transparent)material.needsUpdate=true;material.opacity=1;material.transparent=false;material.depthWrite=true}this.editor.open(cloneModel(this.player.model))}
 changeModel(model:VoxelModel){if(performance.now()-this.lastEditSound>90){this.sound.play('edit');this.lastEditSound=performance.now()}const actor=this.player;const pivotDelta=new THREE.Vector3(...model.pivot).sub(new THREE.Vector3(...actor.model.pivot)).applyAxisAngle(UP,actor.yaw);this.physics.teleport(actor.physical,actor.position.clone().add(pivotDelta));actor.model=cloneModel(model);actor.bounds=modelBounds(model);actor.volume=modelVolume(model);this.selectedModel=cloneModel(model);updateModelView(actor.visual,model);this.physics.resize(actor.physical,actor.bounds)}
 async models(){this.input.unlock();const select=(model:VoxelModel)=>{if(this.running&&this.player?.role==='hider'){const result=this.physics.validateEdit({...model,pivot:this.player.model.pivot},this.player.model,this.player.position,this.player.yaw);if(!result.valid){this.ui.toast(result.reason??'这里放不下这个模型');return false}this.changeModel(model)}else this.selectedModel=cloneModel(model);this.ui.toast(`${translate('已选择「')}${model.name}${translate('」')}`,false);return true};try{this.libraryClose=await openModelLibrary(document.querySelector('#editor-root')!,model=>{select(model)},m=>this.ui.toast(m,false),{onClose:()=>{this.libraryClose=undefined;if(this.running&&!this.editor.active)this.resume()},onEdit:this.running&&this.player?.role==='hider'?model=>{if(select(model))this.editor.open(cloneModel(this.player.model))}:undefined})}catch{this.ui.toast('模型库读取失败，请检查浏览器本地存储权限')}}
 taunt(actor:Actor,forced=false){if(!actor.alive||actor.role!=='hider'||!canTauntPhase(this.session.phase,forced))return;if(!forced&&!tauntReady(this.session.elapsed,actor.lastTaunt))return;if(forced)actor.lastForced=this.session.elapsed;else{actor.lastTaunt=this.session.elapsed;if(this.session.phase==='hunt')actor.score+=10}this.sound.play(forced?'forced':'taunt',actor.position);this.bots.hear(actor,this.actors,this.session.elapsed);this.effects.burst(actor.position.clone().add(new THREE.Vector3(0,actor.bounds.max[1]+4)),forced?0xeeb97c:0xb6d8b0,4);if(actor.id===0&&!forced)this.ui.toast(this.session.phase==='practice'?'口哨已响起，5 秒后可再次发声':'主动发声 +10 分；附近猎人可能听到了')}
 damaged(actor:Actor,killer?:Actor){if(actor.id===0){this.ui.hurt();this.sound.play('hurt');if(actor.role==='hunter'&&!killer)this.ui.toast(`误击场景实体，损失生命`)}if(!actor.alive){actor.velocity.set(0,0,0);if(actor.id===0){if(this.editor.active)this.editor.close();this.firstPerson=false;this.ui.toast('你已出局，积分保留。现在可以自由观战')}else if(killer?.id===0)this.ui.toast(`发现 ${actor.name}！+100 分`)}}
 onPhase(previous:Phase){const phase=this.session.phase;if(phase==='hunt'){for(const a of this.actors)a.lastForced=this.session.elapsed;let n=0;for(const a of this.actors)if(a.role==='hunter'){const pos=new THREE.Vector3(...this.map.hunterSpawn);pos.x+=(n++-.5)*35;pos.y+=.2;this.physics.teleport(a.physical,pos);a.velocity.set(0,0,0)}this.bots.beginHunt(this.actors,this.session.elapsed);this.sound.play('roundStart');this.ui.toast(this.player.role==='hunter'?'猎杀开始：观察可疑物件，误击实体会扣血':'猎杀开始。建模仍可使用，注意主动与强制发声')}
  if(phase==='reveal'){if(this.editor.active)this.editor.close();this.input.unlock();this.revealOrder=this.actors.filter(a=>a.role==='hider').sort((a,b)=>a.score-b.score);this.sound.play('reveal');for(const a of this.actors){a.rig?.setFirstPerson(false);a.visual.visible=true;const material=a.visual.userData.voxelState?.material as THREE.MeshStandardMaterial|undefined;if(material){if(material.transparent)material.needsUpdate=true;material.opacity=1;material.transparent=false;material.depthWrite=true}}}
  if(phase==='preparation'&&previous==='reveal'){this.createRound(true);this.ui.hud();this.resume();this.announceRole()}
 }
 controls(dt:number){const p=this.player;if(!p)return;const input=this.input;if(input.tap('Tab'))this.toggleEditor();if(this.editor.active)return;if(input.tap('KeyV')){this.firstPerson=!this.firstPerson;this.ui.toast(this.firstPerson?'第一人称视角':'第三人称视角')}if(!input.locked)return;this.yaw-=input.dx*.002*this.settings.sensitivity;this.pitch=THREE.MathUtils.clamp(this.pitch-input.dy*.002*this.settings.sensitivity,-1.38,1.35);input.dx=input.dy=0;
  if(!p.alive){const forward=new THREE.Vector3(0,0,-1).applyEuler(new THREE.Euler(this.pitch,this.yaw,0,'YXZ'));const right=new THREE.Vector3(1,0,0).applyAxisAngle(UP,this.yaw);const movement=new THREE.Vector3().addScaledVector(forward,Number(input.key('KeyW','ArrowUp'))-Number(input.key('KeyS','ArrowDown'))).addScaledVector(right,Number(input.key('KeyD','ArrowRight'))-Number(input.key('KeyA','ArrowLeft')));movement.y+=Number(input.key('Space'))-Number(input.key('ControlLeft','ControlRight'));this.rendering.camera.position.addScaledVector(movement.normalize(),dt*(input.key('ShiftLeft','ShiftRight')?180:85));this.rendering.camera.rotation.set(this.pitch,this.yaw,0,'YXZ');return}
  p.pitch=this.aimAngles().pitch;p.aim=p.role==='hunter'&&input.buttons.has(2);p.sprint=input.key('ShiftLeft','ShiftRight');if(p.role==='hunter'){const wantsCrouch=input.key('ControlLeft','ControlRight'),bounds={min:HUNTER_BOUNDS.min,max:[9,wantsCrouch?41:48,7] as Vec3};if(wantsCrouch||this.physics.canFit(bounds,p.position,p.yaw)){p.crouch=wantsCrouch;if(p.bounds.max[1]!==bounds.max[1]){p.bounds=bounds;this.physics.resize(p.physical,bounds)}}}
  if(p.role==='hunter'){if(input.tap('Digit1'))this.combat.switch(p,'knife');if(input.tap('Digit2')||input.tap('Digit3'))this.combat.switch(p,p.gun);if(input.wheel!==0)this.combat.switch(p,p.weapon==='knife'?p.gun:'knife');if(input.tap('KeyR'))this.combat.reload(p);if(input.buttons.has(0)){if(this.rackSelection()){if(input.clicked.has(0))this.takeRackWeapon();}else if(this.combat.shoot(p,this.aimDirection(),this.session.phase))this.recoil.add(p.weapon,p.aim)}}
  if(input.tap('KeyT'))this.taunt(p);const axis=new THREE.Vector3(Number(input.key('KeyD','ArrowRight'))-Number(input.key('KeyA','ArrowLeft')),0,Number(input.key('KeyS','ArrowDown'))-Number(input.key('KeyW','ArrowUp'))).normalize().applyAxisAngle(UP,this.yaw);this.moveActor(p,axis,p.sprint,input.tap('Space'),dt,this.yaw,p.role==='hider'&&input.key('ControlLeft','ControlRight')?new THREE.Vector2(Number(input.key('KeyD','ArrowRight'))-Number(input.key('KeyA','ArrowLeft')),Number(input.key('KeyW','ArrowUp'))-Number(input.key('KeyS','ArrowDown'))):undefined)
 }
 moveActor(actor:Actor,direction:THREE.Vector3,sprint:boolean,jump:boolean,dt:number,yaw?:number,climbInput?:THREE.Vector2){
  if(!actor.alive)return;actor.sprint=sprint;const targetYaw=yaw??(direction.lengthSq()>.001?Math.atan2(-direction.x,-direction.z):actor.yaw);actor.previousYaw=actor.yaw;actor.yaw=targetYaw;
  let state=this.climbers.get(actor.id);if(!state){state={normal:new THREE.Vector3(),cooldown:0,active:false};this.climbers.set(actor.id,state)}state.cooldown=Math.max(0,state.cooldown-dt);
  const surface=climbInput&&state.cooldown===0?this.physics.climbSurface(actor.physical):undefined;
  state.active=!!surface&&actor.role==='hider'&&actor.stun<=0;
  let delta:THREE.Vector3;
  if(state.active&&surface&&climbInput){
   state.normal.copy(surface.normal);actor.velocity.set(0,0,0);
   if(jump){this.sound.play('jump',actor.position);state.active=false;state.cooldown=.28;actor.velocity.copy(surface.normal).multiplyScalar(MOTION.wallKick);actor.velocity.y=MOTION.wallKickUp;delta=actor.velocity.clone().multiplyScalar(dt)}
   else{
    const tangent=UP.clone().cross(surface.normal),right=new THREE.Vector3(1,0,0).applyAxisAngle(UP,actor.yaw);if(tangent.dot(right)<0)tangent.negate();
    actor.velocity.copy(tangent).multiplyScalar(climbInput.x*MOTION.climb);actor.velocity.y=climbInput.y*MOTION.climb;
    if(climbInput.y>0&&actor.position.y+actor.bounds.min[1]>=surface.top+.12){actor.velocity.addScaledVector(surface.normal,-MOTION.climb);actor.velocity.y=0}
    delta=actor.velocity.clone().multiplyScalar(dt);
   }
  }else{
   let speed=sprint?108:66;if(actor.crouch)speed=38;if(actor.stun>0)speed=0;
   if(state.cooldown===0){const response=actor.stun>0?3:actor.role==='hunter'?(direction.lengthSq()>.001?10:14):16;const blend=1-Math.exp(-dt*response);actor.velocity.x=THREE.MathUtils.lerp(actor.velocity.x,direction.x*speed,blend);actor.velocity.z=THREE.MathUtils.lerp(actor.velocity.z,direction.z*speed,blend)}
   if(actor.physical.grounded&&actor.velocity.y<0)actor.velocity.y=-2;if(jump&&actor.physical.grounded&&actor.stun<=0){actor.velocity.y=MOTION.jump;this.sound.play('jump',actor.position)}actor.velocity.y-=MOTION.gravity*dt;delta=actor.velocity.clone().multiplyScalar(dt);
  }
  const oldY=actor.position.y,wasGrounded=actor.physical.grounded,fallSpeed=actor.velocity.y;this.physics.move(actor.physical,delta,actor.yaw);actor.yaw=actor.physical.yaw;if(!wasGrounded&&actor.physical.grounded&&fallSpeed<-35)this.sound.play('land',actor.position);if(state.active&&actor.velocity.lengthSq()>4&&this.session.elapsed-actor.lastStep>.3){actor.lastStep=this.session.elapsed;this.sound.play('climb',actor.position)}
  if(actor.velocity.y>0&&Math.abs(actor.position.y-oldY)<.001){actor.velocity.y=0;if(state.active&&actor.id===0&&this.session.elapsed-this.climbFeedbackAt>2){this.ui.toast('上方空间不足，无法继续攀爬');this.climbFeedbackAt=this.session.elapsed}}
  if(needsPreparationReturn(this.session.phase,actor.role,actor.position.toArray(),actor.bounds,actor.yaw)||actor.position.y<-60||Math.abs(actor.position.x)>1400||Math.abs(actor.position.z)>900){const safe=new THREE.Vector3(...(actor.role==='hunter'&&this.session.phase==='preparation'?this.preparationPosition(Math.max(0,this.actors.filter(a=>a.role==='hunter').findIndex(a=>a.id===actor.id))):this.map.hiderSpawn));safe.y+=.2;this.physics.teleport(actor.physical,safe);actor.velocity.set(0,0,0)}
  if(actor.physical.grounded&&direction.lengthSq()>.1&&!state.active&&this.session.elapsed-actor.lastStep>(sprint?.28:.45)){actor.lastStep=this.session.elapsed;this.sound.play('step',actor.position,'pistol',this.surfaceAt(actor.position))}
 }

 simulate(dt:number){const phase=this.session.phase;if(!this.running||phase==='menu'||phase==='sessionEnd')return;const active=this.editor.active||((this.input.locked||this.inspectionActive)&&this.ui.screen==='game')||phase==='reveal';if(!active)return;
  if(phase!=='reveal'){this.recoil?.update(dt);(this.map.group.userData.practiceRange as PracticeRange|undefined)?.update(dt);this.controls(dt);for(const a of this.actors){this.combat.update(a,dt);if(!a.alive){a.deadTime+=dt;continue}if(a.id!==0){const intent=this.bots.decide(a,this.actors,phase,dt,this.session.elapsed);const aim=a.role==='hunter'?aimBot(a,intent,dt,this.session.elapsed):undefined;let kick:Recoil|undefined;if(aim){this.botRecoil??=new Map();kick=this.botRecoil.get(a.id);if(!kick){kick=new Recoil();this.botRecoil.set(a.id,kick)}kick.update(dt);aim.direction.applyAxisAngle(new THREE.Vector3(1,0,0).applyAxisAngle(UP,a.yaw),kick.pitch).applyAxisAngle(UP,kick.yaw)}this.moveActor(a,intent.direction,intent.sprint,intent.jump,dt,aim?a.yaw:undefined);if(aim?.canFire&&intent.attack&&this.combat.shoot(a,aim.direction,phase))kick?.add(a.weapon,a.aim);if(intent.taunt)this.taunt(a)}if(a.role==='hider'){if(phase==='hunt'){const center=a.position.clone().add(new THREE.Vector3(0,Math.max(2,a.bounds.max[1]/2),0));const near=this.actors.some(h=>h.alive&&h.role==='hunter'&&h.position.distanceTo(a.position)<120&&Math.abs(h.position.y-a.position.y)<48&&this.physics.visible(center,h.position.clone().add(new THREE.Vector3(0,30,0))));a.score+=scoreRate(a.volume,near)*dt;if(a.id===0)this.nearHunter=near;for(const hunter of this.actors)if(hunter.role==='hunter')if(this.combat.ram(a,hunter)&&a.id===0)this.ui.toast('冲撞成功 +25 分！')}const interval=this.session.settings.forcedTauntSeconds;if(phase==='hunt'&&interval>0&&this.session.elapsed-a.lastForced>=interval)this.taunt(a,true)}}this.physics.step(dt)}
  const previous=this.session.phase;this.session.advance(dt,this.actors.filter(a=>a.alive&&a.role==='hider').length,this.actors.filter(a=>a.alive&&a.role==='hunter').length);if(previous!==this.session.phase)this.onPhase(previous)
 }
 updateVisuals(dt:number){for(const a of this.actors){a.visual.position.copy(a.position);a.visual.traverse(o=>o.layers.set(sampleRoomPosition(a.position)?1:0));a.visual.rotation.y=a.yaw;if(a.rig){a.rig.setFirstPerson(a.id===0&&this.firstPerson&&a.alive&&this.session.phase!=='reveal');a.rig.update(dt,{speed:Math.hypot(a.velocity.x,a.velocity.z),sprint:a.sprint,grounded:a.physical.grounded,crouch:a.crouch,aim:a.aim,pitch:a.pitch+(a.id===0?0:this.botRecoil?.get(a.id)?.pitch??0),turn:THREE.MathUtils.euclideanModulo(a.yaw-a.previousYaw+Math.PI,2*Math.PI)-Math.PI,weapon:a.weapon,shot:a.shotTimer/.16,reload:a.reloadTimer/WEAPONS[a.gun].reload,melee:a.meleeTimer/.4,hurt:a.hurtTimer/.3,dead:a.alive?0:1,knockdown:Math.min(1,a.knockdown*4),switchWeapon:a.switchTimer/.35})}else{a.visual.visible=!(a.id===0&&this.firstPerson&&!this.editor.active&&a.alive);if(!a.alive&&this.session.phase!=='reveal')a.visual.scale.setScalar(Math.max(.01,1-a.deadTime*2));else a.visual.scale.setScalar(1)}}}
 menuCamera(dt:number){this.menuTime+=dt;const desired=new THREE.Vector3(...this.map.menuCamera);const target=new THREE.Vector3(...this.map.menuTarget);const orbit=desired.sub(target).applyAxisAngle(UP,Math.sin(this.menuTime*.08)*.075);this.rendering.camera.position.copy(target).add(orbit);this.rendering.camera.lookAt(target);this.rendering.camera.fov=48;this.rendering.camera.updateProjectionMatrix()}
 updateCamera(dt:number){if(!this.running){this.menuCamera(dt);return}if(this.editor.active){this.editor.update(dt);this.rendering.camera.position.copy(this.physics.cameraPosition(this.editor.cameraTarget,this.rendering.camera.position));this.rendering.camera.lookAt(this.editor.cameraTarget);this.rendering.camera.updateMatrixWorld(true);return}const camera=this.rendering.camera,p=this.player;if(!p)return;if(this.session.phase==='reveal'){const index=Math.min(this.revealOrder.length-1,Math.floor(this.session.phaseElapsed/(this.session.revealDuration/Math.max(1,this.revealOrder.length))));const focus=this.revealOrder[index];if(focus){focus.visual.scale.setScalar(1);const target=new THREE.Box3().setFromObject(focus.visual).getCenter(new THREE.Vector3());let desired=this.physics.cameraPosition(target,target.clone().add(new THREE.Vector3(55,38,62)));if(desired.distanceTo(target)<25){for(let i=0;i<8;i++){const candidate=this.physics.cameraPosition(target,target.clone().add(new THREE.Vector3(Math.sin(i*Math.PI/4)*65,18,Math.cos(i*Math.PI/4)*65)));if(candidate.distanceTo(target)>desired.distanceTo(target))desired=candidate}}camera.position.lerp(desired,1-Math.exp(-dt*2.2));camera.position.copy(this.physics.cameraPosition(target,camera.position));camera.lookAt(target);this.highlight.visible=true;this.highlight.setFromObject(focus.visual)}return}if(!p.alive)return;
  const desiredHeight=p.role==='hunter'?((p.crouch?27:42)-Math.min(1,p.knockdown*4)*24):Math.max(4,p.bounds.max[1]*.65);this.eyeHeight=THREE.MathUtils.lerp(this.eyeHeight,desiredHeight,1-Math.exp(-dt*16));const speed=Math.hypot(p.velocity.x,p.velocity.z);this.cameraStride+=dt*speed*.12;const bob=p.role==='hunter'&&p.physical.grounded?Math.sin(this.cameraStride*2)*Math.min(.55,speed/160)*(p.aim?.3:1):0;const target=p.position.clone().add(new THREE.Vector3(0,this.eyeHeight+bob,0)),angles=this.aimAngles();if(this.firstPerson){camera.position.copy(target);camera.rotation.set(angles.pitch,angles.yaw,0,'YXZ')}else{const radius=p.role==='hunter'?100:Math.max(58,p.bounds.max[1]*2.2);const offset=new THREE.Vector3(0,0,radius).applyEuler(new THREE.Euler(angles.pitch,angles.yaw,0,'YXZ'));offset.y+=p.role==='hunter'?9:16;const desired=this.physics.cameraPosition(target,target.clone().add(offset));camera.position.copy(desired);camera.lookAt(target);if(p.role==='hider'){const material=p.visual.userData.voxelState?.material as THREE.MeshStandardMaterial|undefined;if(material){const height=Math.max(8,p.bounds.max[1]-p.bounds.min[1]),opacity=THREE.MathUtils.clamp((camera.position.distanceTo(target)/height-.6)/1.1,.18,1);if(material.transparent!==(opacity<1))material.needsUpdate=true;material.opacity=opacity;material.transparent=opacity<1;material.depthWrite=opacity===1}}}camera.fov=THREE.MathUtils.lerp(camera.fov,p.aim&&p.weapon!=='knife'?48:68,1-Math.exp(-dt*14));camera.updateProjectionMatrix();}
 roomAt(position:THREE.Vector3){return this.map.rooms.find(r=>position.x>=r.min[0]&&position.x<=r.max[0]&&position.y>=r.min[1]&&position.y<r.max[1]&&position.z>=r.min[2]&&position.z<=r.max[2])?.name??'Garden'}
 surfaceAt(position:THREE.Vector3):'wood'|'tile'|'grass'{const room=this.roomAt(position);return /\u82b1\u56ed|\u9662|Garden/.test(room)?'grass':/\u53a8\u623f|\u536b\u751f/.test(room)?'tile':'wood'}
 hud(){const p=this.player;if(!p)return;const room=this.map.rooms.find(r=>p.position.x>=r.min[0]&&p.position.x<=r.max[0]&&p.position.y>=r.min[1]&&p.position.y<r.max[1]&&p.position.z>=r.min[2]&&p.position.z<=r.max[2]);const index=Math.min(this.revealOrder.length-1,Math.floor(this.session.phaseElapsed/(this.session.revealDuration/Math.max(1,this.revealOrder.length))));this.ui.update({phase:this.session.phase,round:this.session.round,remaining:this.session.remaining,actor:p,aliveHiders:this.actors.filter(a=>a.alive&&a.role==='hider').length,aliveHunters:this.actors.filter(a=>a.alive&&a.role==='hunter').length,multiplier:this.nearHunter?2:1,cooldown:Math.max(0,5-(this.session.elapsed-p.lastTaunt)),weapon:p.weapon,ammo:p.ammo,reserve:p.reserve,reloading:p.reloadTimer>0,room:room?.name??'阳光花园',editing:this.editor.active,locked:this.input.locked||this.inspectionActive,nearWeaponStation:this.nearWeaponStation(),rackWeapon:this.rackSelection(),trainingScore:(this.map.group.userData.practiceRange as PracticeRange|undefined)?.total??0,winner:this.session.winner,reveal:this.revealOrder[index],rank:this.revealOrder,fps:this.fps})}
 frame(time:number){if(this.disposed)return;const dt=Math.min(.1,this.lastTime?(time-this.lastTime)/1000:1/60);this.lastTime=time;this.frameCount++;this.fpsTimer+=dt;if(this.fpsTimer>1){this.fps=this.frameCount/this.fpsTimer;this.frameCount=0;this.fpsTimer=0}this.accumulator=Math.min(this.accumulator+dt,.15);let steps=0;while(this.accumulator>=1/60){this.simulate(1/60);this.accumulator-=1/60;if(++steps===1){this.input.pressed.clear();this.input.clicked.clear()}}this.updateVisuals(dt);this.updateCamera(dt);this.sound.updateListener(this.rendering.camera.position,this.rendering.camera.getWorldDirection(new THREE.Vector3()));this.sound.updateAmbience(dt,this.player?this.roomAt(this.player.position):'',this.running&&(this.input.locked||this.inspectionActive)&&!this.editor.active);this.sound.updateMusic(this.session.phase,this.session.remaining,this.session.phase!=='menu'&&!((this.running&&(this.editor.active||((this.input.locked||this.inspectionActive)&&this.ui.screen==='game')||this.session.phase==='reveal'))||this.session.phase==='sessionEnd'));this.effects.update(dt);this.hudTimer+=dt;if(this.running&&this.hudTimer>.1){this.hud();this.hudTimer=0}this.rendering.render();if(steps>0)this.input.endFrame();requestAnimationFrame(t=>this.frame(t))}
 snapshot(){return{phase:this.session.phase,round:this.session.round,remaining:this.session.remaining,elapsed:this.session.elapsed,fps:this.fps,editing:this.editor.active,firstPerson:this.firstPerson,locked:this.input.locked,drawCalls:this.rendering.renderer.info.render.calls,actors:this.actors.map(a=>({id:a.id,name:a.name,role:a.role,position:a.position.toArray(),hp:a.hp,alive:a.alive,score:a.score,total:a.total,volume:modelVolume(a.model),grounded:a.physical.grounded,ammo:a.ammo,weapon:a.weapon}))}}
}
