import {translate,getLanguage,setLanguage,onLanguageChange,localizeElement} from './i18n.ts';
import type {ActorState,GameSettings,Phase,WeaponId} from './contracts.ts';import {DEFAULT_SETTINGS,normalizeSettings,recommendSettings,scoreRate} from './session.ts';
import {modelVolume} from './voxel/model.ts';
const esc=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export interface UIActions {start:(mode:'practice'|'hunt',quick?:boolean)=>void;menu:()=>void;resume:()=>void;settings:(s:GameSettings)=>void;models:()=>void;end:()=>void;edit:()=>void;next:()=>void;audio?:(cue:boolean)=>void;audioPreview?:(volume:number,musicVolume:number)=>void;}
export interface HUDData {phase:Phase;round:number;remaining:number;actor:ActorState;aliveHiders:number;aliveHunters:number;multiplier:number;cooldown:number;weapon:WeaponId;ammo:number;reserve:number;reloading:boolean;room:string;editing:boolean;locked:boolean;nearWeaponStation?:boolean;rackWeapon?:WeaponId|null;trainingScore?:number;winner:string;reveal?:ActorState;rank:ActorState[];fps:number;}
export class UI {
 root:HTMLElement;actions:UIActions;settings:GameSettings;screen='loading';toastNode:HTMLElement;toastUntil=0;lastPhase:Phase='menu';lastRound=0;lastHUD?:HUDData;lastActors:ActorState[]=[];
 constructor(root:HTMLElement,actions:UIActions,settings:GameSettings){this.root=root;this.actions=actions;this.settings=settings;this.toastNode=document.querySelector('#toast')!;this.toastNode.setAttribute('role','status');this.toastNode.setAttribute('aria-live','polite');
  onLanguageChange(()=>{this.toastNode.classList.remove('show');if(this.screen==='menu')this.menu();else if(this.screen==='pause'){this.hud();if(this.lastHUD)this.update(this.lastHUD);this.pause()}else if(this.screen==='game'){this.hud();if(this.lastHUD)this.update(this.lastHUD)}else if(this.screen==='totals')this.totals(this.lastActors)});
  root.addEventListener('pointerdown',()=>actions.audio?.(false),true);
  root.addEventListener('keydown',e=>{if(!e.repeat)actions.audio?.(false)},true);
  root.addEventListener('click',e=>{const button=(e.target as HTMLElement).closest<HTMLButtonElement>('button');if(button&&!button.disabled)actions.audio?.(true)},true);
  root.addEventListener('click',e=>{const el=(e.target as HTMLElement).closest<HTMLElement>('[data-action]');if(!el)return;const action=el.dataset.action;switch(action){case'language':setLanguage(getLanguage()==='en'?'zh-CN':'en');break;case'hunt':actions.start('hunt');break;case'practice':actions.start('practice');break;case'quick-hunter':actions.start('hunt',true);break;case'settings':this.showSettings();break;case'models':actions.models();break;case'menu':actions.menu();break;case'resume':actions.resume();break;case'end':actions.end();break;case'edit':actions.edit();break;case'next':actions.next();break}})}
 languageButton(){return `<button type="button" class="language-switch" data-action="language" aria-label="${getLanguage()==='en'?'Switch to Chinese':'Switch to English'}"><span lang="zh-CN">中文</span><span aria-hidden="true"> / </span><span lang="en">English</span></button>`}
 loading(message:string){this.root.innerHTML=`<div class="loading"><div class="brand-mark">H</div><p>${esc(message)}</p><span>HIDEAWAY · 藏物公馆</span></div>`}
 toast(message:string,translateMessage=true){this.toastNode.textContent=translateMessage?translate(message):message;this.toastNode.classList.add('show');window.clearTimeout(this.toastUntil);this.toastUntil=window.setTimeout(()=>this.toastNode.classList.remove('show'),3500)}
 menu(){this.screen='menu';this.root.dataset.role='menu';this.root.innerHTML=`<div class="menu-scrim"></div>${this.languageButton()}<header class="brand"><span class="brand-mark"><svg viewBox="0 0 48 48" aria-hidden="true"><path d="M8 22 24 9 40 22v20H8Z"/><path d="M19 42V29h10v13M15 22h4m10 0h4"/><circle cx="24" cy="20" r="3"/></svg></span><span>藏物公馆<small>${getLanguage()==='en'?'P R O P H U N T':'H I D E A W A Y'}</small></span></header><div class="menu-content"><p class="eyebrow"><span class="status-dot"></span>今日也有一点不对劲</p><h1>藏得<span>刚刚好。</span></h1><p class="menu-description">做一只安静的杯子，或成为发现秘密的人。<br>阳光住宅里，一场小小的捉迷藏即将开始。</p><div class="menu-buttons"><button class="primary" data-action="hunt"><span class="menu-icon" aria-hidden="true">▶</span><span>开始回合<small>与本地 Bot 一起 · 准备 / 猎杀 / 揭晓</small></span><span class="button-arrow">↗</span></button><button class="secondary" data-action="practice"><span class="menu-icon" aria-hidden="true">◇</span><span>自由练习<small>无限探索 · 体素创作 · 保存伪装</small></span><span class="button-arrow">↗</span></button></div><div class="role-preference"><span>下一轮身份偏好</span><div role="group" aria-label="身份偏好">${[['random','?','随机'],['hider','◇','躲藏者'],['hunter','⌖','猎人']].map(([value,icon,label])=>`<button data-role="${value}" aria-pressed="${this.settings.role===value}" class="${this.settings.role===value?'selected':''}"><i aria-hidden="true">${icon}</i>${label}</button>`).join('')}</div><small>随机时，每位角色成为猎人的机会相同</small></div><div class="menu-links"><button data-action="models"><span aria-hidden="true">▦</span> 我的模型</button><button data-action="settings"><span aria-hidden="true">⚙</span> 游戏设置</button></div></div><aside class="house-ticket"><span class="ticket-label">欢迎来到 · 晴日住宅</span><div class="ticket-illustration" aria-hidden="true"><span>?</span><svg viewBox="0 0 130 95"><path d="M35 70V27h46v43q0 16-23 16T35 70Z"/><path d="M81 35h10q23 0 18 19T81 66"/><ellipse cx="58" cy="27" rx="23" ry="8"/><path class="steam" d="M45 9q-5 6 0 11m17-13q-5 6 0 11"/></svg></div><b>这里的每件小事，<br>都可能是你的朋友。</b><p>复式住宅 / 阳光花园 / 自由建模</p><div class="ticket-stamp">离线游玩<small>与机器人一起游玩</small></div></aside><footer class="menu-footer"><span>ORIGINAL LITTLE SECRETS · 藏物公馆</span><span>WASD 移动　 /　 TAB 建模　 /　 V 切换视角</span></footer>`;localizeElement(this.root);this.root.querySelectorAll<HTMLButtonElement>('[data-role]').forEach(button=>button.addEventListener('click',()=>{this.settings=normalizeSettings({...this.settings,role:button.dataset.role as GameSettings['role']});this.actions.settings(this.settings);this.menu()}))}

 hud(){this.screen='game';this.root.innerHTML=`<div class="hud-top"><div class="room-badge"><span class="tiny-label">HIDEAWAY · 藏物公馆</span><b id="room-name">晴日住宅</b></div><div class="phase-badge"><span id="phase-name">准备藏好</span><strong id="timer">06:00</strong><small id="round-label">第 1 局</small></div><div class="score-badge"><span class="tiny-label">本局积分</span><strong id="score">0</strong><span id="multiplier">×1.0</span></div></div><div id="phase-announcement" class="phase-announcement"></div><div id="crosshair" class="crosshair"><i></i><i></i><i></i><i></i></div><div id="hitmarker" class="hitmarker">×</div><div id="damage-flash"></div><div id="hud-bottom"><div class="player-card"><span id="role-label" class="tiny-label">躲藏者</span><div class="health-line"><b id="hp">100</b><div class="health-track"><i id="hp-fill"></i></div><span>HP</span></div><p id="live-count">仍在躲藏</p></div><div class="ability-card"><span id="ability-key">T</span><div><b id="ability-name">吹声口哨</b><small id="ability-detail">冒一点险，多一点分</small></div></div><div class="weapon-card" id="weapon-card"><span id="weapon-name">手枪</span><strong><b id="ammo">12</b><small id="reserve"> / 96</small></strong><span id="weapon-hint">1 匕首 · 2 枪械 · R 换弹</span></div></div><div class="game-controls" id="game-controls">WASD 移动 <span>SHIFT 冲刺</span> SPACE 跳跃 <span>V 视角</span> TAB 建模 <span>T 发声</span></div><button class="pause-button" data-action="menu" aria-label="暂停游戏">Ⅱ</button><div id="unlock-hint" class="unlock-hint"><button data-action="resume">点击继续游玩 <span>↗</span></button><small>ESC 释放鼠标　·　游戏已暂停</small></div><div id="reveal-card"></div><div id="death-card"></div>`;localizeElement(this.root)}
 update(data:HUDData){this.lastHUD=data;if(this.screen!=='game')return;const set=(id:string,text:string)=>{text=translate(text);const e=this.root.querySelector<HTMLElement>('#'+id);if(e&&e.textContent!==text)e.textContent=text};const player=data.actor,training=data.phase==='preparation'&&player.role==='hunter',station=training&&data.nearWeaponStation,rackWeapon=station?data.rackWeapon:null;this.root.dataset.role=player.role;const phaseNames:Record<Phase,string>={menu:'',practice:'自由练习',preparation:'准备藏好',hunt:'猎杀进行中',reveal:'位置揭晓',sessionEnd:'本场结束'};
 set('phase-name',phaseNames[data.phase]);set('timer',Number.isFinite(data.remaining)?`${Math.floor(data.remaining/60).toString().padStart(2,'0')}:${Math.floor(data.remaining%60).toString().padStart(2,'0')}`:'∞');set('round-label',`第 ${data.round} 局`);set('score',Math.floor(player.score).toLocaleString());set('multiplier',player.role==='hider'&&data.phase==='hunt'&&player.alive?`${scoreRate(modelVolume(player.model),data.multiplier>1).toFixed(1)} 分/秒`:'不计时得分');set('room-name',data.room);set('role-label',`${player.role==='hider'?'躲藏者':'猎人'} · ${player.name}`);set('hp',`${Math.ceil(player.hp)}`);const hp=this.root.querySelector<HTMLElement>('#hp-fill');if(hp)hp.style.width=`${Math.max(0,player.hp)}%`;set('live-count',`${data.aliveHiders} 位躲藏者  /  ${data.aliveHunters} 位猎人`);
 const weaponNames={knife:'匕首',pistol:'手枪',smg:'冲锋枪',shotgun:'霰弹枪'};
 set('ability-key',player.role==='hider'?'T':station?'左键':'R');
 set('ability-name',player.role==='hider'?(!['hunt','practice'].includes(data.phase)?'尚未开放':data.cooldown>0?`${data.cooldown.toFixed(1)} 秒`:'吹声口哨'):rackWeapon?`取用${weaponNames[rackWeapon]}`:station?'武器架':data.reloading?'正在换弹':training?'靶场练习':'准备就绪');
 set('ability-detail',player.role==='hider'?(data.phase==='hunt'?'方向声音 · 风险奖励 +10':data.phase==='practice'?'试听声音 · 不计分':'猎杀开始后可用'):rackWeapon?`左键取用${weaponNames[rackWeapon]} · 补满弹药`:station?'瞄准武器架上的武器，左键取用':training?`练靶 ${data.trainingScore??0} 分 · 回合不计分`:'打空气不扣血，误击实体扣血');
 set('weapon-name',weaponNames[data.weapon]);set('ammo',data.weapon==='knife'?'∞':String(data.ammo));set('reserve',data.weapon==='knife'?'':` / ${data.reserve}`);set('weapon-hint',training?'武器架左键取枪 · R 换弹':'1 匕首 · 2 枪械 · R 换弹');const weapon=this.root.querySelector<HTMLElement>('#weapon-card');if(weapon)weapon.hidden=player.role!=='hunter';
 const unlock=this.root.querySelector<HTMLElement>('#unlock-hint');if(unlock)unlock.hidden=data.locked||data.editing||data.phase==='reveal';const crosshair=this.root.querySelector<HTMLElement>('#crosshair');if(crosshair){crosshair.hidden=data.editing||!player.alive||data.phase==='reveal';crosshair.classList.toggle('hider-crosshair',player.role==='hider')}
 const bottom=this.root.querySelector<HTMLElement>('#hud-bottom');if(bottom)bottom.hidden=data.editing||data.phase==='reveal';
 const controls=this.root.querySelector<HTMLElement>('#game-controls');if(controls){controls.hidden=data.editing||data.phase==='reveal';controls.textContent=!player.alive?'自由观战 · WASD 飞行 · SHIFT 加速 · SPACE 上升 · CTRL 下降':player.role==='hunter'?`WASD 移动 · SHIFT 冲刺 · CTRL 蹲伏 · SPACE 跳跃 · V 视角 · 右键瞄准 · R 换弹${training?' · 准备区自由射击 · 武器架左键取枪':''}`:`WASD 移动 · SHIFT 冲刺 · CTRL 爬墙 · SPACE 跳跃 / 蹬离 · V 视角 · TAB 建模${data.phase==='hunt'||data.phase==='practice'?' · T 发声':''}`;}
 if(controls&&controls.textContent)controls.textContent=translate(controls.textContent);
 const resume=this.root.querySelector<HTMLElement>('#unlock-hint [data-action=resume]');if(resume)resume.textContent=player.alive?'点击继续游玩 ↗':'点击进入自由观战 ↗';
 if(resume&&resume.textContent)resume.textContent=translate(resume.textContent);
 const death=this.root.querySelector<HTMLElement>('#death-card');if(death){death.hidden=player.alive||data.phase==='reveal';death.innerHTML=player.alive?'':`<div class="death-banner"><small>你已被发现</small><b>保留 ${Math.floor(player.score)} 积分</b><p>自由观战 · WASD 飞行 · SPACE 上升 · CTRL 下降</p></div>`}
 if(death)localizeElement(death);
 const reveal=this.root.querySelector<HTMLElement>('#reveal-card');if(reveal){reveal.hidden=data.phase!=='reveal';if(data.phase==='reveal')reveal.innerHTML=`<div class="reveal-panel"><span class="eyebrow">${esc(data.winner)} · 位置揭晓</span><h2>${esc(data.reveal?.name??'本局结束')}</h2><strong>${Math.floor(data.reveal?.score??0)}<small> 分</small></strong><p>从低到高，看看谁藏得最好。</p><div class="reveal-ranking">${data.rank.map((a,i)=>`<span>${i+1}. ${esc(a.name)} <b>${Math.floor(a.score)}</b></span>`).join('')}</div></div>`}
 if(reveal)localizeElement(reveal);
 if(data.phase!==this.lastPhase||data.round!==this.lastRound){this.lastPhase=data.phase;this.lastRound=data.round;const banner=this.root.querySelector<HTMLElement>('#phase-announcement');if(banner){banner.innerHTML=data.phase==='preparation'?`<small>第 ${data.round} 局 · 本轮身份</small><b>你是${player.role==='hunter'?'猎人':'躲藏者'}</b><span>${player.role==='hunter'?'西墙按 E 补给 · 射击线后向东练靶 · 准备结束进入住宅':'找到藏点 · TAB 自由建模 / CTRL 爬墙 · 发声尚未开放'}</span>`:data.phase==='hunt'?`<b>${player.role==='hunter'?'猎杀开始，寻找可疑物品。':'猎人出发了，保持伪装。'}</b>`:'';localizeElement(banner);banner.classList.add('visible');setTimeout(()=>banner.classList.remove('visible'),4400)}}
 }
 pause(){this.screen='pause';this.root.insertAdjacentHTML('beforeend',`<div class="modal-backdrop" id="pause-dialog"><section class="dialog compact"><span class="eyebrow">稍作休息</span><h2>游戏已暂停</h2>${this.languageButton()}<button class="primary" data-action="resume">继续游玩 ↗</button><button class="plain-button" data-action="settings">游戏设置</button><button class="plain-button" data-action="end">结束本场，查看总分</button><button class="plain-button" data-action="menu">返回主菜单</button></section></div>`);localizeElement(this.root)}
 showSettings(){const previous=this.screen;this.screen='settings';const s=this.settings;const old=this.root.querySelector('#settings-dialog');old?.remove();this.root.insertAdjacentHTML('beforeend',`<div class="modal-backdrop" id="settings-dialog"><form class="dialog settings-dialog"><span class="eyebrow">按你的节奏来</span><h2>游戏设置</h2><div class="settings-grid"><label>玩家人数 <input name="players" type="number" min="2" max="8" value="${s.players}"></label><label>猎人人数 <input name="hunters" type="number" min="1" max="7" value="${s.hunters}"></label><label>准备时长 / 秒 <input name="preparationSeconds" type="number" min="5" max="900" value="${s.preparationSeconds}"></label><label>猎杀时长 / 秒 <input name="huntSeconds" type="number" min="10" max="1800" value="${s.huntSeconds}"></label><label>小物随机比例 <input name="randomRatio" type="range" min="0" max="1" step="0.05" value="${s.randomRatio}"><output>${Math.round(s.randomRatio*100)}%</output></label><label>强制发声 / 秒 <input name="forcedTauntSeconds" type="number" min="0" max="180" value="${s.forcedTauntSeconds}"><small>0 为关闭，与主动发声独立</small></label><label>正常回合身份偏好 <select name="role"><option value="random" ${s.role==='random'?'selected':''}>随机 · 每轮公平抽签</option><option value="hider" ${s.role==='hider'?'selected':''}>躲藏者</option><option value="hunter" ${s.role==='hunter'?'selected':''}>猎人</option></select></label><label>猎人枪械 <select name="gun">${[['pistol','手枪 · 精准'],['smg','冲锋枪 · 高射速'],['shotgun','霰弹枪 · 近身爆发']].map(([v,t])=>`<option value="${v}" ${s.gun===v?'selected':''}>${t}</option>`).join('')}</select></label><label>总音量 <input name="volume" type="range" min="0" max="1" step=".05" value="${s.volume}"></label><label>背景音乐 <input name="musicVolume" type="range" min="0" max="1" step=".05" value="${s.musicVolume}"></label><label>鼠标灵敏度 <input name="sensitivity" type="range" min=".2" max="3" step=".1" value="${s.sensitivity}"></label><label>画质 <select name="quality"><option value="high" ${s.quality==='high'?'selected':''}>高 · 阴影与环境遮蔽</option><option value="medium" ${s.quality==='medium'?'selected':''}>中 · 优先帧率</option></select></label></div><p class="settings-note">默认准备 6 分钟 / 猎杀 8 分钟。偏好在每轮开始时分配实际身份，练习始终为躲藏者。人数与回合配置在下次开始生效。</p><div class="dialog-actions"><button type="button" class="plain-button" id="settings-reset">恢复默认</button><button class="primary" type="submit">保存设置</button></div></form></div>`);
 localizeElement(this.root);
 const dialog=this.root.querySelector('#settings-dialog')!;const form=dialog.querySelector('form')!;const previewAudio=()=>this.actions.audioPreview?.(Number(form.querySelector<HTMLInputElement>('[name=volume]')!.value),Number(form.querySelector<HTMLInputElement>('[name=musicVolume]')!.value));for(const name of ['volume','musicVolume'])form.querySelector<HTMLInputElement>('[name='+name+']')!.addEventListener('input',previewAudio);const ratio=form.querySelector<HTMLInputElement>('[name=randomRatio]')!;ratio.addEventListener('input',()=>{form.querySelector('output')!.value=`${Math.round(Number(ratio.value)*100)}%`});form.querySelector<HTMLInputElement>('[name=players]')!.addEventListener('input',e=>{const count=Number((e.target as HTMLInputElement).value);if(count>=2&&count<=8){const suggested=recommendSettings(count);for(const [key,value]of Object.entries(suggested))form.querySelector<HTMLInputElement>('[name='+key+']')!.value=String(value);form.querySelector<HTMLInputElement>('[name=hunters]')!.max=String(count-1)}});form.querySelector('#settings-reset')!.addEventListener('click',()=>{this.settings={...DEFAULT_SETTINGS};this.actions.audioPreview?.(this.settings.volume,this.settings.musicVolume);dialog.remove();this.screen=previous;this.showSettings()});form.addEventListener('submit',e=>{e.preventDefault();const data=new FormData(form);const values:Record<string,unknown>={};for(const[k,v]of data)values[k]=['role','gun','quality'].includes(k)?v:Number(v);this.settings=normalizeSettings(values as Partial<GameSettings>);this.actions.settings(this.settings);dialog.remove();this.screen=previous;if(previous==='menu')this.menu();this.toast('设置已保存')});(form.querySelector('input') as HTMLInputElement).focus();
 }
 totals(actors:ActorState[]){this.lastActors=actors;this.screen='totals';this.root.innerHTML=`<div class="modal-backdrop"><section class="dialog totals-dialog"><span class="eyebrow">这一场，藏得漂亮</span><h2>本场总排行榜</h2><div class="total-list">${[...actors].sort((a,b)=>b.total+b.score-a.total-a.score).map((a,i)=>`<div><span>${String(i+1).padStart(2,'0')}</span><b>${esc(a.name)}</b><strong>${Math.floor(a.total+a.score)}<small> 分</small></strong></div>`).join('')}</div><button class="primary" data-action="menu">返回公馆 ↗</button></section></div>`;localizeElement(this.root)}
 hit(){const e=this.root.querySelector('#hitmarker');e?.classList.add('active');setTimeout(()=>e?.classList.remove('active'),150)}hurt(){const e=this.root.querySelector('#damage-flash');e?.classList.add('active');setTimeout(()=>e?.classList.remove('active'),250)}
}
